name: Run Go tests

on:
  - push

jobs:

  Test:
    runs-on: ubuntu-20.04

    defaults:
      run:
        # For tests, we need the path to be the Github repository path for proper stack traces in the tests.
        working-directory: github.com/kohofinancial/errors

    steps:
      - uses: actions/checkout@v3.5.2
        with:
          path: github.com/kohofinancial/errors

      - name: Setup Go
        uses: actions/setup-go@v4.0.0
        with:
          go-version-file: github.com/kohofinancial/errors/go.mod

      - name: Test
        run: go test -v ./...
