name: Publish UpCloud Provider

on:
  push:
    tags: ["v0.*"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GOOS: linux
  GOARCH: amd64

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: feat/cluster-autoscaler-cloudprovider-upcloud

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_PAT }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build Go binary
        working-directory: cluster-autoscaler/
        env:
          GOOS: ${{ env.GOOS }}
          GOARCH: ${{ env.GOARCH }}
          CGO_ENABLED: "0"
        run: go build -ldflags "-w -s" --tags upcloud -o cloudprovider/upcloud/cluster-autoscaler-${{ env.GOARCH }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: cluster-autoscaler/Dockerfile.${{ env.GOARCH }}
          context: cluster-autoscaler/cloudprovider/upcloud/
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
